language: php

php:
  - 5.6
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install

script: 
    - php bin/tabular report examples/books/books.xml examples/books/report.json
    - php bin/tabular report examples/phpbench/phpbench.xml examples/phpbench/report.json
    - php bin/tabular report examples/phpunit/tests.xml examples/phpunit/cases.json
